# Generated by Django 2.2 on 2019-04-17 19:07

from django.db import migrations, models
import mrt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(db_index=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mrt.models.upload_path_handler)),
            ],
        ),
    ]
